TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#DB += prosilica.db
#DB += plugins.db
DB += calibrate.db
DB += thumbnails.db

#DB_INSTALLS+= $(AREAD)/db/ADBase.template 
#DB_INSTALLS+= $(AREAD)/db/prosilica.template 
#DB_INSTALLS+= $(AREAD)/db/NDFile.template 
#DB_INSTALLS+= $(AREAD)/db/NDPluginBase.template
#DB_INSTALLS+= $(AREAD)/db/NDStdArrays.template
#DB_INSTALLS+= $(AREAD)/db/NDFileTIFF.template
#DB_INSTALLS+= $(AREAD)/db/NDFileJPEG.template
#DB_INSTALLS+= $(AREAD)/db/NDROI.template
#DB_INSTALLS+= $(AREAD)/db/NDProcess.template
#DB_INSTALLS+= $(AREAD)/db/NDStats.template
#DB_INSTALLS+= $(AREAD)/db/NDTransform.template
#DB_INSTALLS+= $(AREAD)/db/NDOverlay.template
#DB_INSTALLS+= $(AREAD)/db/NDOverlayN.template

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

